name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build_main
        run: |
          gcc main.c uCShell.c -o uCShell

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./*.exe*
